- chapter01_crashcourse/linear-regression-scratch.md
Fix for
http://discuss.gluon.ai/t/topic/331
> Fix weight sign

- chapter00_preface/install.md
> minor update for windows users

- chapter01_crashcourse/reg-gluon.md
- chapter01_crashcourse/reg-scratch.md
- chapter01_crashcourse/underfit-overfit.md
Better than previous params :)
> Add regularization from scratch, update params, and re-write overfitting/regularization with gluon

- chapter03_gluon-basics/use-gpu.md
> remove haha variable in use-gpu.md

- chapter05_recurrent-neural-networks/rnn-scratch.md
put the bias inside the bracket
> correct minor error in RNN formula

- chapter04_convolutional-neural-networks/cnn-scratch.md
> fix cnn stride

- chapter04_convolutional-neural-networks/cnn-scratch.md
#权重格式是input_filter x output_filter x height x width
改为
#output_channels x in_channels x height x width
> fix a annotation in cnn-scratch

- chapter_optimization/adam-gluon.md
> fix typo in adam-gluon: adadelta -> adam

- README.md
> fix spelling problem

- utils.py
> Fix misspelling

- chapter_recurrent-neural-networks/bptt.md
fix a typo when reading the tutorials.
valishing to vanishing
> fix type in bptt

- chapter_computer-vision/fcn.md
[Fix FCN typo issues](https://discuss.gluon.ai/t/topic/5712/10)
> fix FCN typo

- chapter_natural-language-processing/nmt.md
Support batch_size for the encoder/decoder. The train_batch_size is still 1 but the encoder/decoder support arbitrary batch_size now.
> Support batch_size for encoder/decoder in the NMT example

- chapter_natural-language-processing/sentiment-analysis.md
1. Change tokenizer to simple space based splitter to meet the efficiency
2. Add one more exercise about using advanced tokenizer
> Change tokenizer in sentiment analysis example

- chapter_supervised-learning/mlp-gluon.md
- chapter_supervised-learning/mlp-scratch.md
- chapter_supervised-learning/multi-layer.md
Made several changes to make the writing probably more smooth.
> Fix grammars/typos in the MLP chapters

- chapter_introduction/deep-learning-intro-en.md
> Translation of introduction to deep learning

- chapter_supervised-learning/linear-regression-scratch.md
- 在dataiter中删掉 num_examples
- 感觉3.2.1有点重复，特别是从前面章一直读下来。
> linear reg scratch

- chapter_natural-language-processing/embedding-training.md
- Replaces mx.nd with nd
- Removes use of numpy
- Assimilates training loop to http://zh.gluon.ai/chapter_recurrent-neural-networks/rnn-gluon.html
- Removes spacing for imports
- Consistent indentation for function (4 spaces)
> Update  chapter_natural-language-processing/embedding-training.md

- chapter_natural-language-processing/embedding-training.md
> Update chapter_natural-language-processing/embedding-training.md 

- chapter_deep-learning-basics/softmax-regression-scratch.md
reduce the training time from 50sec to 7sec.
> update dataloader in mlp

- chapter_appendix/jupyter.md
> 更改Notebook首字母

- chapter_computer-vision/anchor.md
- chapter_computer-vision/yolo.md.bak
- chapter_deep-learning-basics/softmax-regression-scratch.md
- chapter_optimization/gd-sgd-gluon.md
There're places in context where NumPy is written as numpy. The latter is used as imported module.
> use NumPy's formal name

- chapter_natural-language-processing/embedding-training.md
> Word embedding mask

- chapter_computer-vision/fine-tuning.md
> small typo

- chapter_deep-learning-basics/mlp-gluon.md
- chapter_deep-learning-basics/mlp.md
v0.7版本书中3.7.2章节 61页倒数第二行l从何而来，貌似没有说明就直接使用了，你看看啊
>  v0.7版本书中3.7.2章节 61页倒数第二行l从何而来，貌似没有说明就直接使用了

- chapter_deep-learning-basics/mlp-gluon.md
- chapter_deep-learning-basics/mlp.md
Reverts mli/gluon-tutorials-zh#345
merged by mistake.
> Revert " v0.7版本书中3.7.2章节 61页倒数第二行l从何而来，貌似没有说明就直接使用了"

- chapter_deep-learning-basics/mlp-gluon.md
- chapter_deep-learning-basics/mlp.md
- chapter_deep-learning-basics/weight-decay.md
> 发现错误【真是一本好书，为可以贡献自己的一份力而自豪！】

- chapter_computer-vision/object-detection-dataset.md
fix typo in object-detection-dataset.md
> fix object-detection-dataset

- chapter_optimization/gd-sgd.md
the example in multidimensional gradient descend f(x)=x_1^2+2x_2 miss square，so fix it to  f(x)=x_1^2+2x_2^2
> fix function f(x)=x_1^2+2x_2^2 in chapter_optimization gd-sgd.md

- chapter_deep-learning-basics/kaggle-house-price.md
This pull request is to solve the problem that the statement is not smooth in kaggle-house-price.md.
> Solve the problem that the statement is not smooth and logical mistake about feature 'MSZoning'.

- chapter_computer-vision/semantic-segmentation-and-dataset.md
change “../data” to “../data路径”, and "../data/VOCdevkit/VOC2012" to "../data/VOCdevkit/VOC2012路径"
> fix typo in semantic-segmentation-and-dataset.md

- chapter_computer-vision/neural-style.md
Change 'Imagenet' to official name 'ImageNet'
> Change Imagenet to ImageNet

- img/linreg.svg
> change direction up to down

- img/linreg.svg
We decided not to go up to down to be consistent with most other liteatature
> Revert "change direction up to down"

- environment.yml
> Fix a dependent

- chapter_deep-learning-basics/kaggle-house-price.md
> Delete useless param in kaggle-house-price.md

- chapter_appendix/aws.md
> Update aws.md-Spelling mistakes

- chapter_prerequisite/install.md
为pip设置国内镜像，解决MXNet的GPU版本下载过慢与安装失败问题。
> add pip settings

- chapter_deep-learning-basics/kaggle-house-price.md
> Revert "Update kaggle-house-price.md"

- chapter_computer-vision/kaggle-gluon-cifar10.md
reorg_test重复, 第一处应该为read_label_file
> typo in kaggle-cifar10

- chapter_optimization/adam.md
epsilon should be outside of sqrt instead of inside (the code is right, the equation has the typo)
> update equation of adam

- chapter_deep-learning-basics/linear-regression-scratch.md
This pull request is to fix a code bug of the 'squared_loss' fuction.
> add nd.sum function to the squared_loss function

- chapter_deep-learning-basics/linear-regression-scratch.md
> Revert "add nd.sum function to the squared_loss function"

- chapter_natural-language-processing/beam-search.md
Reverts d2l-ai/d2l-zh#515 for further edits
> Revert "对beam search集束搜索章节的相关改写"

- chapter_installation/index.md
> modified:   chapter_installation/index.md

- chapter_installation/index.md
- config.ini
sudo apt update && sudo apt install nvidia-cuda-toolkit -y
> nvcc程序ubuntu安装命令

- chapter_attention-mechanisms/attention-scoring-functions.md
- chapter_attention-mechanisms/nadaraya-waston.md
Easy to read and understand.
Complete some equation description.
> Correct some translation errors.

- chapter_preface/index.md
I try to create a new brach and to create a new PR with one file.
> add my name in preface/index.md

- chapter_computer-vision/kaggle-dog.md
> 13.14 kaggle dog

- chapter_deep-learning-computation/custom-layer.md
1. Add 'tab' corresponding to different name of defined class 'MyDense' and 'MyLinear';
2. Change following instance name from 'dense' to 'linear' for 'pytorch' tab, to make it more elegant (N.B. this will conflict with original english version)
3. Modify "汇总" to "降维", corresponding to recent PR #816
> translation in custom-layer

- chapter_preface/index.md
Please consider my name in the acknowlegement if I may. Thanks !
> Add my name into preface

- chapter_computer-vision/kaggle-cifar10.md
- chapter_computer-vision/kaggle-dog.md
Fixes for [issue](https://github.com/d2l-ai/d2l-en/issues/1775).
Refer:
MXNet:
https://github.com/d2l-ai/d2l-en/commit/8b325e369d3723fd3d700a2c5356afcb135ff818
https://github.com/d2l-ai/d2l-en/commit/2827fe50b227052bbc5b5ebc8948baebac955da1
https://github.com/d2l-ai/d2l-en/commit/aa2a9a3e041b684ae434a9af470e8aa92aa26fb8
https://github.com/d2l-ai/d2l-en/commit/0da9c0646ddc6e6c8c9512296414ccbf4bdb9857
PyTorch:
https://github.com/d2l-ai/d2l-en/pull/1783/files
https://github.com/d2l-ai/d2l-en/pull/1784/files
> [WIP] Improve performance on the Kaggle small-scale CIFAR-10 and ImageNet Dog dataset

- chapter_notation/index.md
修改关于相对补集的不正确表述，应为: A\B={x|x∈A, 且x not∈ B}
> modify the meaning expression about chapter_notation

- chapter_installation/index.md
Align with https://github.com/d2l-ai/d2l-en/blame/master/chapter_installation/index.md
> Installation Updates

- chapter_recurrent-modern/bi-rnn.md
- chapter_recurrent-modern/machine-translation-and-dataset.md
> [polish] chapter 9 peer review 2

- chapter_convolutional-neural-networks/conv-layer.md
> Fix: Epoch instead of batch

- chapter_natural-language-processing-applications/sentiment-analysis-and-dataset.md
- chapter_natural-language-processing-applications/sentiment-analysis-rnn.md
> [polish] chapter 15 peer review 2

- chapter_computational-performance/multiple-gpus.md
- chapter_computational-performance/multiple-gpus_origin.md
@AnirudhDagar 
The previous pull request was too messy, so I deleted it and re-forked it
Thanks for your advice and forgive my poor python knowledge.
Do you think it's ok to change the source code to this?
---
The problem with the code is that it does not synchronize data to all gpus, as shown in the following code.
```python
%matplotlib inline
from d2l import torch as d2l
import torch
from torch import nn
from torch.nn import functional as F
def allreduce(data):
for i in range(1, len(data)):
data[0][:] += data[i].to(data[0].device)
for i in range(1, len(data)):
data[i] = data[0].to(data[i].device)
test_rd = [torch.ones((1, 2), device=d2l.try_gpu(0)),torch.ones((1, 2), device=d2l.try_gpu(1))*2]
data = [test_rd[i] for i in range(2)]
print('before allreduce:\n', test_rd[0], '\n', …
```
> Troubleshoot the data synchronization failure

- chapter_computer-vision/semantic-segmentation-and-dataset.md
- d2l/torch.py
Mirror changes from https://github.com/d2l-ai/d2l-en/pull/1980.
> [PyTorch] Fix semantic segmentation normalization

- chapter_linear-networks/linear-regression-concise.md
> Align exercise with the english version

- chapter_attention-mechanisms/self-attention-and-positional-encoding.md
10.6.3. Positional Encoding, '2j列' -> '2j+1列'
> 2j列 -> 2j+1列

- Jenkinsfile
- chapter_computer-vision/kaggle-dog.md
- chapter_linear-networks/linear-regression.md
- setup.py
- static/build.yml
This PR helps move d2l-zh to the upgraded CI.
> MAINT: Update CI, Update frameworks, Pin Deps

- chapter_installation/index.md
@xiaotinghe 
Please review and merge the lib version updates. Importantly, please get these changes and https://github.com/d2l-ai/d2l-zh/pull/1095 synced with the publisher.
> Upgrade lib versions

- chapter_deep-learning-computation/parameters.md
Unify naming of the function 'init_xavier()'.
> Unify the function naming

- chapter_recurrent-neural-networks/sequence.md
- chapter_recurrent-neural-networks/sequence_origin.md
> fix the imprecise description

- chapter_computer-vision/anchor.md
> Use the passed in parameter instead of 0.5

- Jenkinsfile
- chapter_installation/index.md
- static/build.yml
Follow up to https://github.com/d2l-ai/d2l-en/pull/2235/.
> BLD: Bump python support version 3.9

- chapter_attention-mechanisms/attention-cues.md
- chapter_attention-mechanisms/attention-scoring-functions.md
- chapter_attention-mechanisms/bahdanau-attention.md
- chapter_attention-mechanisms/multihead-attention.md
- chapter_attention-mechanisms/nadaraya-waston.md
- chapter_attention-mechanisms/self-attention-and-positional-encoding.md
- chapter_attention-mechanisms/transformer.md
- chapter_computational-performance/async-computation.md
- chapter_computational-performance/auto-parallelism.md
- chapter_computational-performance/hybridize.md
- chapter_computational-performance/multiple-gpus-concise.md
- chapter_computational-performance/multiple-gpus.md
- chapter_optimization/adadelta.md
- chapter_optimization/adagrad.md
- chapter_optimization/adam.md
- chapter_optimization/convexity.md
- chapter_optimization/gd.md
- chapter_optimization/lr-scheduler.md
- chapter_optimization/minibatch-sgd.md
- chapter_optimization/momentum.md
- chapter_optimization/optimization-intro.md
- chapter_optimization/rmsprop.md
- chapter_optimization/sgd.md
- chapter_recurrent-modern/bi-rnn.md
- chapter_recurrent-modern/deep-rnn.md
- chapter_recurrent-modern/encoder-decoder.md
- chapter_recurrent-modern/gru.md
- chapter_recurrent-modern/lstm.md
- chapter_recurrent-modern/machine-translation-and-dataset.md
- chapter_recurrent-modern/seq2seq.md
【Paddle】add discussion for paddle chap 9-12
> 【Paddle】add discussion for paddle chap 9-12

- chapter_computer-vision/anchor.md
- chapter_computer-vision/bounding-box.md
- chapter_computer-vision/fcn.md
- chapter_computer-vision/fine-tuning.md
- chapter_computer-vision/image-augmentation.md
- chapter_computer-vision/kaggle-cifar10.md
- chapter_computer-vision/kaggle-dog.md
- chapter_computer-vision/multiscale-object-detection.md
- chapter_computer-vision/neural-style.md
- chapter_computer-vision/object-detection-dataset.md
- chapter_computer-vision/rcnn.md
- chapter_computer-vision/semantic-segmentation-and-dataset.md
- chapter_computer-vision/ssd.md
- chapter_computer-vision/transposed-conv.md
- chapter_natural-language-processing-applications/natural-language-inference-and-dataset.md
- chapter_natural-language-processing-applications/natural-language-inference-attention.md
- chapter_natural-language-processing-applications/natural-language-inference-bert.md
- chapter_natural-language-processing-applications/sentiment-analysis-and-dataset.md
- chapter_natural-language-processing-applications/sentiment-analysis-cnn.md
- chapter_natural-language-processing-applications/sentiment-analysis-rnn.md
- chapter_natural-language-processing-pretraining/bert-dataset.md
- chapter_natural-language-processing-pretraining/bert-pretraining.md
- chapter_natural-language-processing-pretraining/bert.md
- chapter_natural-language-processing-pretraining/similarity-analogy.md
- chapter_natural-language-processing-pretraining/subword-embedding.md
- chapter_natural-language-processing-pretraining/word-embedding-dataset.md
- chapter_natural-language-processing-pretraining/word2vec-pretraining.md
【Paddle】add discussion for paddle chap13-1
【Paddle】add discussion for paddle chap13-2
【Paddle】add discussion for paddle chap13-3
【Paddle】add discussion for paddle chap13-4
【Paddle】add discussion for paddle chap13-5
【Paddle】add discussion for paddle chap13-6
【Paddle】add discussion for paddle chap13-7
【Paddle】add discussion for paddle chap13-8
【Paddle】add discussion for paddle chap13-9
【Paddle】add discussion for paddle chap13-10
【Paddle】add discussion for paddle chap13-11
【Paddle】add discussion for paddle chap13-12
【Paddle】add discussion for paddle chap13-13
【Paddle】add discussion for paddle chap13-14
【Paddle】add discussion for paddle chap14-3
【Paddle】add discussion for paddle chap14-4
【Paddle】add discussion for paddle chap14-6
【Paddle】add discussion for paddle chap14-7
【Paddle】add …
> 【Paddle】add discussion for paddle chap13+chap15
