d2l-ai/d2l-zh

chapter_convolutional-neural-networks/cnn-scratch.md, utils.py
- the commit of "make user can load existing dataset from any folder"
MXNET `load_data_fashion_mnist` function take "~/.mxnet/datasets/fashion-mnist" as the default save folder, if the dataset is not there it will download again. As some users may manager the public dataset by themselves,  I add a parameter to let user can pass their own path of dataset folder.
=> make user can load existing dataset from any folder

environment.yml
gluon应该是基于python3开发，但由于很多人默认的python版本为python2，直接使用`conda env create -f environment.yml`则会创建python2为版本的虚拟环境。这样会带来很多不便，如
https://discuss.gluon.ai/t/topic/3399/9 和 https://discuss.gluon.ai/t/topic/2511/45?u=hlnull 。
在environment.yaml中设定python版本应该可以强制安装python3的虚拟环境。
=> 避免创建python版本为2的虚拟环境

utils.py
解决大家AlexNet train不好的问题。其原因是，在utils.py里的load_data_fashion_mnist中的tramsform函数在处理mnist数据集的时候，resize 成224之后的ndarray 除以 255 会等于0。
解决办法是让resize操作在DataLoader这里做，而不是在 gluon.data.vision.FashionMNIST这里做。更详细的讨论可以参见https://discuss.gluon.ai/t/topic/1258/59的44楼，48楼，52楼，57楼。
代码credit to gluon论坛里的 @xiaoming
=> fix for resize to 224 when training AlextNet in alexnet-gluon.md

utils.py
There are some Chinese punctuation in utils.py. It looks strange, and Python2 users couldn't import it because of these non-ascii characters.
=> Fix Chinese punctuation in utils.py

chapter_deep-learning-basics/mlp-gluon.md
Change-Id: I4f410d7fb6e58201628e646b7a167ba4af11c92f
Found the running result on tutorial is not good (Tutorial link https://zh.gluon.ai/chapter_deep-learning-basics/mlp-gluon.html).
After investigation, I think **the second "net.add(nn.Dense(10))" in the sector In[2] is not necessary, and need remove it**, as:
**1. it's not the design as the early text and diagram.
2. there will be a bigger parameter dict here.**
Before remove the second "net.add(nn.Dense(10))", net.collect_params() returns:
sequential0_ (
Parameter dense0_weight (shape=(256, 784), dtype=float32)
Parameter dense0_bias (shape=(256,), dtype=float32)
Parameter dense1_weight (shape=(10, 256), dtype=float32)
Parameter dense1_bias (shape=(10,), dtype=float32)
Parameter dense2_weight (shape=(10, 10), dtype=float32)
Parameter …
=> remove unnecessary Dense from mlp-gluon net

chapter_natural-language-processing/embedding-training.md
A global variable was used instead of the local variable in the correct scope.
=> Fix typo / scope issue

build/build_doc.sh
Starting with conda v4.4, `source activate` is discouraged. The CI server now runs conda 4.5 so the Jenkinsfile needs to be adapted.
=> Update Jenkinsfile for CI server conda upgrade

chapter_prerequisite/ndarray.md
2.2.6小节，在展示`numpy.array`转换为`mx.nd.ndarray`的时候，没有使用刚刚新建的`numpy`数组`p`，而是上节中的`x`。如下所示：
```
import numpy as np
p = np.ones((2, 3))
d = nd.array(x)
d
```
应该改为：
```
import numpy as np
p = np.ones((2, 3))
d = nd.array(p)
d
```
见论坛讨论链接：https://discuss.gluon.ai/t/topic/7429/23?u=crazyai
=> fix typo in ndarray/numpy transform example

chapter_convolutional-neural-networks/densenet.md
This pr is to fix spelling mistake `desnet` to `densenet` in densenet.md
=> fix spelling mistake `desnet` to `densenet` in densenet.md

chapter_computer-vision/image-augmentation.md
9.1.1章节 变形小节中第一句"左右翻转图片通常不物体的类别"改为"左右翻转图片通常不改变物体的类别"
=> fix a missing word

chapter_deep-learning-basics/linear-regression-gluon.md
Due to multiple changes the exercise description doesn't match with the code. little typo
=> fix typos in linear-regression-gluon.md

chapter_computer-vision/neural-style.md
minior change to fix the print out.
=> change learning rate and logging criterion

chapter_computer-vision/image-augmentation.md
两个augs操作并不专用于训练/测试，名字存在误导，修改后更易于理解。
=> 两个augs操作并不专用于训练/测试，名字存在误导，修改后更易于理解。

chapter_deep-learning-basics/kaggle-house-price.md
log_rmse()是一个泛用的损失函数，其定义不应该只接受train_features，而且事实上在后面`def train()`函数里也调用了`log_rmse(net, test_features, test_labels)`  
修改成`log_rmse(net, features, labels)`更容易理解，不会引起误导
=> update param name of log_rmse() in kaggle-house-price.md

chapter_deep-learning-basics/linear-regression.md
fix a typo in a formula, w -> \theta
=> fix typo in linear-regression.md: w -> \theta

chapter_convolutional-neural-networks/googlenet.md
There should be activation functions after convolution layers in the second block of googlenet
=> add activation functions in block2 of googlenet

chapter_convolutional-neural-networks/batch-norm.md
After BtchNorm, we need to use two hyper-params to shift output from linear region: gamma and beta, which should be initialized as 1 and 0, but the annotation is reversed, which may results into misunderstanding.
=> Batch-norm: modify an annotation

chapter_linear-networks/softmax-regression.md
原文“证明 $\lambda^{-1} \mathrm{RealSoftMax}(\lambda a, \lambda b)$成立”应对应与3.1同样的证明，但是缺少了">"后面的表达式，所以补全为“证明 $\lambda^{-1} \mathrm{RealSoftMax}(\lambda a, \lambda b) > \mathrm{max}(a, b)$成立”以消除歧义。
=> 明确练习3.2中的证明表达式

setup_origin.py
% `flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics`
```
./d2l-zh/setup_origin.py:3:13: E999 SyntaxError: invalid decimal literal
commit: 9e55a9c
^
./d2l-zh/d2l/tensorflow.py:727:18: F821 undefined name 'get_params'
params = get_params(len(vocab), num_hiddens)
^
1     E999 SyntaxError: invalid decimal literal
1     F821 undefined name 'get_params'
2
```
=> Fix Python syntax error in setup_origin.py

chapter_recurrent-modern/seq2seq.md
Mirroring https://github.com/d2l-ai/d2l-en/pull/1981.
Question: I'm not sure why d2l-zh has no saved `bleu` function in the d2l package even though we have added #@save in the notebook. Any ideas @goldmermaid? Hence I only fixed the notebook code for this, but in the English version the libraries were also updated.
=> BUG: Fix BLEU calculation

chapter_attention-mechanisms/attention-scoring-functions.md
changed `tf.constant([2, 3]))` to `tf.constant([[1, 3], [2, 4]]))` to align with pytorch and mxnet code
=> fix typo in tensorflow code

chapter_preface/index.md, d2l/__init__.py, d2l/paddle.py, static/build.yml
To use saved functions from paddle we need to build from source since d2l==0.17.4 or any d2l released version doesn't support the saved paddle methods.
This PR makes the necessary changes to build paddle from source and lib `d2l/paddle` for utilization of saved methods.
cc @cheungdaven @astonzhang
=> [Paddle] Fix missing d2l lib for paddle

chapter_optimization/lr-scheduler.md
+ Correct a translation error. In previous Chinese edition of ``lr-scheduler.md``, "Factor Scheduler" and "Multi Factor Scheduler" are translated into the same word "多因子调度器" and it might confuse readers before they read the original discourse.
+ Rewrite several sentences because they were incorrectly or improperly statemented due to machine translation.
=> fix: Update the Chinese translation in lr-scheduler.md

chapter_deep-learning-computation/model-construction.md
I think it should be ‘_module’ here, but it is ‘module’ in the book, so I don't know if I understand it correctly.
=> Fix a spelling error

chapter_natural-language-processing-pretraining/glove.md
fix typo in chapter_natural-language-processing-pretraining/glove.md
=> fix typo in chapter_natural-language-processing-pretraining/glove.md

chapter_computer-vision/image-augmentation.md
I have found two problems.
1. the translation "Gluon数据集提供的`transform_first`函数" can be difficult to understand. If the reader does not think carefully, they will not realise that this function is a method of the `Dataset` class, but rather that one of the datasets of `Gluon` contains this function.
2. "即图像顶部的元素" is obviously a wrong translation, it means "i.e. the element at the top of the image.".
=> Correct a translation error.

chapter_computer-vision/anchor.md
Avoids the following user warning:
```python
~/anaconda3/envs/torch/lib/python3.10/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
```
=> Avoid `torch.meshgrid` user warning

chapter_preliminaries/calculus.md
链式法则中，对于多元函数求微分，应该使用偏微分符号。
已对比英文版本并做出修改。
=> [fix] Formula Error

chapter_linear-networks/linear-regression.md
Correct a typo `nucleu` -> `nucleus` in [§3.1.4.2](https://zh.d2l.ai/chapter_linear-networks/linear-regression.html#id12).
Ref: ([English original](https://d2l.ai/chapter_linear-regression/linear-regression.html#biology))
> Consider the cartoonish picture of a biological neuron in [Fig. 3.1.3](https://d2l.ai/chapter_linear-regression/linear-regression.html#fig-neuron), consisting of *dendrites* (input terminals), the *nucleus* (CPU), the *axon* (output wire), and the *axon terminals* (output terminals), enabling connections to other neurons via *synapses*.
=> Correct typo `nucleu` -> `nucleus` in §3.1.4.2
